### PR TITLE
NGSTACK-654 implement twig function for mapping component items

### PR DESCRIPTION
**Pull request by petarjakopec**

### CODE REVIEW

**Comment by emodric** [comment]
Thanks @petarjakopec, however, this should go to https://github.com/netgen/site-bundle

**Comment by emodric** [comment]
I suppose nomenclature here could be made generic? There's no reason why this should have "component" in its name, since it can be used on any content type.

**Comment by emodric** [comment]
How about `ng_grouped_fields` since the arguments to Twig function are `$content` and `$group`?

**Comment by pspanja** [comment]
I like it, but maybe rather `ng_group_fields` as it groups existing fields? We'll rename this when moving to `site-bundle` shortly.

**Comment by emodric** [comment]
Sounds good :+1:

**Pull request merged**
