### PR TITLE
Node 16 support

### PR DESCRIPTION
**Pull request by xrow**
Hi,

this should bring you node 16 support.

### CODE REVIEW

**Comment by emodric** [comment]
Hi!

Thanks for the patch, but it seems that the build is not working 100% as it should. I believe this is an error due to introducing `sass`, rather than using Node 16. Any tips on how to fix this?

DEV build

```
eddie@abyss ~/www/media-site-v3 (master●●●)$ yarn build:dev
yarn run v1.22.19
$ encore dev
Running webpack ...

 ERROR  Failed to compile with 2 errors                                                                                                                                                                 10:03:25 AM

 error  in ./assets/sass/style-noncritical.scss                                                                                                                                                         10:03:25 AM

Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid argument(s): Unsupported output style "nested".

 error  in ./assets/sass/style-noncritical.scss                                                                                                                                                         10:03:25 AM

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid argument(s): Unsupported output style "nested".
    at processResult (/var/www/html/media-site-v3/node_modules/webpack/lib/NormalModule.js:764:19)
    at /var/www/html/media-site-v3/node_modules/webpack/lib/NormalModule.js:866:5
    at /var/www/html/media-site-v3/node_modules/loader-runner/lib/LoaderRunner.js:400:11
    at /var/www/html/media-site-v3/node_modules/loader-runner/lib/LoaderRunner.js:252:18
    at context.callback (/var/www/html/media-site-v3/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/var/www/html/media-site-v3/node_modules/sass-loader/dist/index.js:69:5)

default:
  Entrypoint index [big] 647 KiB = runtime.js 26.2 KiB index.js 621 KiB
  Entrypoint index-noncritical [big] 1.71 MiB = runtime.js 26.2 KiB index-noncritical.js 1.68 MiB
  default compiled with 4 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

PROD build

```
eddie@abyss ~/www/media-site-v3 (master●●●)$ yarn build:prod
yarn run v1.22.19
$ encore production
Running webpack ...

 WARN  Compiled with 5 warnings                                                                                                                                                                         10:03:54 AM

 warn  in index.css?v=bb3187ba420ddc76df55                                                                                                                                                              10:03:54 AM

Css Minimizer Plugin: postcss-svgo: /var/www/html/media-site-v3/index.css?v=bb3187ba420ddc76df55:9:36575: Error: SvgoParserError: <input>:1:1: Non-whitespace before first tag.

> 1 | %3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20'%3e%3cpath fill='no…
    | ^
 

 warn  in index.css?v=bb3187ba420ddc76df55                                                                                                                                                              10:03:54 AM

Css Minimizer Plugin: postcss-svgo: /var/www/html/media-site-v3/index.css?v=bb3187ba420ddc76df55:9:36864: Error: SvgoParserError: <input>:1:1: Non-whitespace before first tag.

> 1 | %3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='2' …
    | ^
 

 warn  in index.css?v=bb3187ba420ddc76df55                                                                                                                                                              10:03:54 AM

Css Minimizer Plugin: postcss-svgo: /var/www/html/media-site-v3/index.css?v=bb3187ba420ddc76df55:9:37120: Error: SvgoParserError: <input>:1:1: Non-whitespace before first tag.

> 1 | %3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 20 20'%3e%3cpath fill='no…
    | ^
 

 warn  in index.css?v=bb3187ba420ddc76df55                                                                                                                                                              10:03:54 AM

Css Minimizer Plugin: postcss-svgo: /var/www/html/media-site-v3/index.css?v=bb3187ba420ddc76df55:9:38362: Error: SvgoParserError: <input>:1:1: Non-whitespace before first tag.

> 1 | %3csvg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='3' …
    | ^
 

 warn  in index.css?v=bb3187ba420ddc76df55                                                                                                                                                              10:03:54 AM

Css Minimizer Plugin: postcss-svgo: /var/www/html/media-site-v3/index.css?v=bb3187ba420ddc76df55:9:91354: Error: SvgoParserError: <input>:1:1: Non-whitespace before first tag.

> 1 | %3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='hsl%280, 0%,…
    | ^
 

default:
  Entrypoint index [big] 466 KiB (2.79 MiB) = runtime.js?v=5c02abda3543f6cf8e3b 2.8 KiB index.css?v=f13059d5db0ce2967226 384 KiB index.js?v=ea717bfd4b372c48e21e 79.1 KiB 16 auxiliary assets
  Entrypoint index-noncritical [big] 274 KiB = runtime.js?v=5c02abda3543f6cf8e3b 2.8 KiB index-noncritical.css?v=31d6cfe0d16ae931b73c 0 bytes index-noncritical.js?v=9428ac88c5112f57d855 271 KiB
  default compiled with 5 warnings
Done in 15.88s.
```

**Comment by xrow** [comment]
For the https://www.npmjs.com/package/postcss-svgo you shall use a non html encoding, but this is a different ticket i guess. Can you cover that?

**Comment by emodric** [comment]
I was trying to fix this, but unsuccessfuly. I'll let this open in hopes it will resolve itself over time. I don't really want to merge this with warnings like these.

**Comment by xrow** [comment]
Ok leave it open...

**Comment by xrow** [comment]
Buy the way, I was able to access the backend and so on. Everything seem to work.

**Comment by emodric** [comment]
Good to know! 👍

**Comment by emodric** [comment]
As media site was upgraded lately to use Node 16/18 due to Ibexa 4.6 upgrade, this is now obsolete, so closing.

**Pull request closed without merging**
