### PR TITLE
[eZ Platform v3] Reduce content view indentation

### PR DESCRIPTION
**Pull request by pspanja**

### CODE REVIEW

**Comment by emodric** [comment]
Can't we just move the file to `config/app/prepends` instead of "hacking" on kernel like this?

**Comment by pspanja** [comment]
Of course, it's just that it wont be on the same place as the rest of the configuration.

**Comment by pspanja** [comment]
How about `prepends/content_view.yaml`?

**Comment by emodric** [comment]
That's true, but since we already have config there, that should be fine.

This is a limitation of kernel loading all files by default, so two folders are not something we can avoid.

I'd rather have it consistent and say `config/app/prepends` is for config loaded via prepending, and `config/packages` for the rest and make sure internally that our team knows the difference and why we have two folders instead of one.

`config/app/prepends/content_view.yaml` sounds okay.

**Comment by pspanja** [comment]
Agreed, updated and amended.

**Pull request merged**
