### PR TITLE
NGSTACK-546: setup eslint and prettier

### PR DESCRIPTION
**Pull request by amalija-ramljak**
- added prettier as a dependency
- added prettier config as `.prettierrc`
- updated eslint-related dependencies that needed an update
- added `eslint-config-prettier` and changed `.eslintrc.json` to remove conflicts with prettier and code formatting
- added comment to `app.js` to tell developers how to remove eslint `no-undef` without disabling the `no-undef` rule for those lines/that file

### CODE REVIEW

**Comment by emodric** [comment]
Looks good, however, `yarn.lock` file should be removed from the PR. The template does not contain lock files, only the projects do.

**Comment by amalija-ramljak** [comment]
@emodric Sorry, wasn't aware of it! Removed with 3f2ca91bcfd44b2700c9aca9d64a65c6c4c7057b

**Comment by iherak** [comment]
FYI @emodric we'll force usage of this through git hooks, same as is done with php-cs-fixer, so this was a necessary start :)

**Comment by emodric** [comment]
@amalija-ramljak Thanks, merging!

@iherak Works for me :)

**Pull request merged**
