### PR TITLE
NGSTACK-770 add 'important' to override ibexa's inline css

### PR DESCRIPTION
**Pull request by draguna1**
Added !important to override Ibexa's inline css

### CODE REVIEW

**Comment by draguna1** [comment]
There were two different styles one was inline from Ibexa, and the other was implemented by Netgen. We had to override Ibexa's style by using the !important property.

**Comment by emodric** [comment]
That much is clear :) But what was the issue with ibexa inline css? What was displayed wrong because of it?

**Comment by draguna1** [comment]
The problem was that the styles were displayed two times. For example, when we used unordered list two bullet would appear side by side.

**Review by Ljudevit — APPROVED** [review]
thanks @draguna1

**Comment by emodric** [comment]
Thanks @draguna1 !

**Pull request merged**
