### PR TITLE
NGSTACK-783 add novactive sitemap configuration

### PR DESCRIPTION
**Pull request by Gintron**

### CODE REVIEW

**Comment by ludwig031** [comment]
@Gintron is there a possibility to change path or default filename for sitemap?
Configuration is siteaccess aware so it would be great if we could have different sitemaps for Bold and Fit&Healthy, along with different sitemaps depending on language (Bold is multi language)
Also, in that case we can take subtree root into account for each siteaccess.

**Comment by ludwig031** [comment]
Also, I have removed everyone except Edi as Assignees and added as Reviewers

**Comment by Gintron** [comment]
All the configuration is siteaccess aware, but having different sitemaps depending on language does not seem to be needed unless the sitemap will exceed file size of 50MB or 50,000 urls

**Review by emodric — APPROVED** [review]

**Review by emodric — CHANGES_REQUESTED** [review]
Discussed needed changes with @ludwig031 , please refer to him.

**Comment by emodric** [comment]
Thanks @Gintron !

**Pull request merged**
