### PR TITLE
NGSTACK-846 config/bundles removed from cs-fixing process by excludin…

### PR DESCRIPTION
**Pull request by ljacmi**
…g it in captainhook

### CODE REVIEW

**Comment by emodric** [comment]
Why?

**Comment by ljacmi** [comment]
> Why

Because cs-fixer forced the relative names of the bundles and use keyword instead of FQNs. @iherak suggested that this should remain as is and to exclude this file from cs-fixing.

**Comment by emodric** [comment]
Sounds good!

**Comment by emodric** [comment]
Thanks @ljacmi !

**Pull request merged**
