### PR TITLE
NGGW-77 Drop console log from production build in webpack config

### PR DESCRIPTION
**Pull request by ludwig031**

### CODE REVIEW

**Comment by emodric** [comment]
Please rebase on `1.11` branch.

**Comment by ludwig031** [comment]
> Please rebase on `1.11` branch.

Done

**Comment by emodric** [comment]
@amalija-ramljak This looks ok to you?

**Comment by amalija-ramljak** [comment]
@emodric looks good, we shouldn't need to log logs or errors or anything (all console fns are caught with this)

**Review by amalija-ramljak — APPROVED** [review]

**Comment by emodric** [comment]
Thanks @ludwig031 & @amalija-ramljak !

**Pull request merged**
