### PR TITLE
Ngstack 658 ibexa4 admin enhancements

### PR DESCRIPTION
**Pull request by petarjakopec**
https://netgen.atlassian.net/browse/NGSTACK-658
I added link from content to its content type and link from content type to search with that content type as filter.

### CODE REVIEW

**Comment by emodric** [comment]
This should go to a separate repo.

**Comment by pspanja** [comment]
@emodric https://github.com/netgen/better-ibexa-admin-ui?

¯\\_(ツ)_/¯

**Comment by emodric** [comment]
If it's ok with you, it's ok with me :)

I'll create a bundle and a composer repo, give me a moment :)

**Comment by emodric** [comment]
@petarjakopec @pspanja Composer package and bundle created. @petarjakopec You can replicate your PR on the repo that @pspanja linked and you can use this PR to just register the bundle in `composer.json` and `config/bundles.php`.

**Comment by emodric** [comment]
Looks good :+1:

**Review by emodric — APPROVED** [review]

**Pull request merged**
