### PR TITLE
[WIP] Ngstack 630 infocollector implementation

### PR DESCRIPTION
**Pull request by PetraMiseta**

### CODE REVIEW

**Comment by emodric** [comment]
@PetraMiseta Thanks for this!

However, all PHP, config and routes should go to https://github.com/netgen/site-bundle, since we implement all backend logic there. `media-site` repo is reserved for frontend code (templates, CSS, JavaScript).

**Comment by pspanja** [comment]
@emodric as mentioned privately, this is a work in progress that first collects everything in one place, we will move the implementation to the proper places before this is ready for the review.

**Comment by pspanja** [comment]
@PetraMiseta I've rebased this for the changes in `bold4`.

**Comment by pspanja** [comment]
Adjusted overridden `ngenhancedlink` view template in https://github.com/netgen/media-site/pull/96/commits/5dd7aa6d3fe355aee41cca2aa8d30b75ad0b8029 (added in https://github.com/netgen/media-site/commit/f4b5c80f18b6b1ecfe4efb261c79175bdcd9dfaa).

**Review by pspanja — APPROVED** [review]

**Pull request merged**
